import { Community } from "./communityTypes";

export const communityCatalog: Community[] = [
  {
    id: "homestead-builders",
    name: "Homestead Builders",
    icon: "HB",
    description:
      "People sharing practical knowledge and helping each other become more capable and independent.",
    tags: ["Self-reliance", "Growing food", "Practical building"],
    specialties: [
      "Carpentry",
      "Gardening",
      "Electrical",
      "Food growing",
      "Mechanical",
    ],
    needs: ["Plumbing", "HVAC", "Welding", "Animal care"],
    level: 14,
    memberCount: 842,
    stats: {
      confirmedContributions: 18420,
      completedTrades: 1284,
      activeContributorsMonth: 386,
      uniqueMembersHelped: 691,
      repeatTradeRate: 62,
      fairTradeRate: 91,
      recentActivity: 418,
      memberGrowthMonth: 7.4,
    },
    createdAt: "2023-04-18",
    leadership: {
      leader: "John Mercer",
      coLeaders: ["Maria Cole", "David Reed"],
      moderatorCount: 4,
    },
    rules: [
      "Keep commitments and communicate directly.",
      "Be honest about your limits.",
      "Respect people, property, and shared tools.",
    ],
    membershipType: "open",
    regions: ["Southeast", "Texas", "Remote"],
  },
  {
    id: "makers-united",
    name: "Makers United",
    icon: "MU",
    description:
      "Builders and repair-minded people exchanging fabrication knowledge and practical help.",
    tags: ["Making", "Repair", "Design"],
    specialties: [
      "Fabrication",
      "Woodworking",
      "Electronics",
      "Design",
      "Repair",
    ],
    needs: ["Welding", "Small engines", "Sewing"],
    level: 11,
    memberCount: 516,
    stats: {
      confirmedContributions: 9940,
      completedTrades: 742,
      activeContributorsMonth: 251,
      uniqueMembersHelped: 403,
      repeatTradeRate: 68,
      fairTradeRate: 94,
      recentActivity: 296,
      memberGrowthMonth: 5.1,
    },
    createdAt: "2024-02-09",
    leadership: {
      leader: "Priya Shah",
      coLeaders: ["Evan Holt"],
      moderatorCount: 3,
    },
    rules: [
      "Describe work accurately.",
      "Use tools safely.",
      "Credit collaborators.",
    ],
    membershipType: "approval",
    regions: ["North America", "Remote"],
  },
  {
    id: "neighbor-network",
    name: "Neighbor Network",
    icon: "NN",
    description:
      "Everyday practical help and dependable connections between nearby people.",
    tags: ["Neighbors", "Everyday help", "Friendship"],
    specialties: ["Home repairs", "Pet care", "Gardening", "Moving", "Cooking"],
    needs: ["Electrical", "Tutoring", "Plumbing"],
    level: 7,
    memberCount: 294,
    stats: {
      confirmedContributions: 4210,
      completedTrades: 388,
      activeContributorsMonth: 126,
      uniqueMembersHelped: 237,
      repeatTradeRate: 55,
      fairTradeRate: 89,
      recentActivity: 151,
      memberGrowthMonth: 8.8,
    },
    createdAt: "2024-10-21",
    leadership: {
      leader: "Amara Brooks",
      coLeaders: ["Sofia Rivera"],
      moderatorCount: 2,
    },
    rules: [
      "Protect private locations.",
      "Confirm plans before arriving.",
      "Leave work areas orderly.",
    ],
    membershipType: "open",
    regions: ["Maplewood", "New Jersey"],
  },
  {
    id: "remote-skills",
    name: "Remote Skills Collective",
    icon: "RS",
    description:
      "Knowledge workers helping others learn, plan, create, and solve problems from anywhere.",
    tags: ["Remote", "Learning", "Digital capability"],
    specialties: [
      "Programming",
      "Design",
      "Tutoring",
      "Bookkeeping",
      "Languages",
    ],
    needs: ["Technical support", "Project planning", "Translation"],
    level: 10,
    memberCount: 631,
    stats: {
      confirmedContributions: 7830,
      completedTrades: 619,
      activeContributorsMonth: 318,
      uniqueMembersHelped: 477,
      repeatTradeRate: 71,
      fairTradeRate: 96,
      recentActivity: 374,
      memberGrowthMonth: 11.2,
    },
    createdAt: "2024-06-12",
    leadership: {
      leader: "Leila Hassan",
      coLeaders: ["Noah Kim", "Ana Silva"],
      moderatorCount: 3,
    },
    rules: [
      "Set a clear session goal.",
      "Protect personal data.",
      "Share limitations early.",
    ],
    membershipType: "open",
    regions: ["Worldwide"],
  },
];
export const getCommunity = (
  id: string | undefined,
  communities: Community[] = communityCatalog,
) => communities.find((c) => c.id === id);
